### ISSUE TITLE
Any operations after logging in fail on macOS

### ISSUE THREAD

**Issue by taumasyang** [Okabe-Rintarou-0/JboxTransferCLI#4]
Logging in was successful, but other operations failed.
```
~ % ./jtrans diff
panic: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

goroutine 1 [running]:
jtrans/db.Init({0x1400022b010, 0xd})
	/github/workspace/db/cli.go:33 +0x240
jtrans/login.prepareDB()
	/github/workspace/login/helper.go:74 +0x70
jtrans/login.init.0()
	/github/workspace/login/helper.go:47 +0xbc
```
- Machine: Mac mini (Late 2020)
- Chip: Apple M1
- OS: macOS Sonoma 14.0 (23A344)
- Binary: `jtrans-v1.0.3-darwin-arm64`

I can provide the debug environment if you don't own an Apple device.

**Comment by Okabe-Rintarou-0** [comment]
Seems to be some build problems, i will handle it

**Comment by Okabe-Rintarou-0** [comment]
You can try release v1.0.4 now

**Comment by taumasyang** [comment]
It's working now, thank you!
